### ISSUE TITLE
get_stats19

### ISSUE THREAD

**Issue by weijia2013** [ropensci/stats19#239]
When I am using:

get_stats19(year = 2005, type = "accidents", data_dir = "XXX"), directory has been replaced. I got error 

No files of that type found for that year.
No files found. Check the stats19 website on data.gov.uk
Files identified: 
Error in if (data_already_exists) { : argument is of length zero

But when I am using:
get_stats19(year = 2005 - 2024, type = "accidents", data_dir = "XXX")

I can download the data from 1979 to 2023, which includes 2005 data. 

Why would this be happening?

**Comment by Robinlovelace** [comment]
Not sure but agree it could be clearer. I will look to fix this. The main issue is that data only exists per year for last 5 years, before that we should default to the huge 1979-2023 dataset. Thanks for reporting and any further feedback or ideas for fix let me know, does the plan outlined above sound good to you (such that if you set `year = 2005` you will get the data from 1979)?

**Comment by weijia2013** [comment]
It sounds a good plan. Thanks for the updating.

**Comment by BlaiseKelly** [comment]
I wondered since so much effort has gone into utilising the local store of the downloaded data it might be helpful to add an extra step to split the 1979-2023 dataset into years. So each file is saved as type_year.RDS and other functions work off that. Would add a little bit of time to the import step, but speed up analysis of multiple years?
